//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int BankId { get; set; }
        public string BankAccName { get; set; }
        public string BankAccNo { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public decimal Balance { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
