//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CmpId { get; set; }
        public string cmpName { get; set; }
        public Nullable<int> BrId { get; set; }
        public string BrName { get; set; }
        public string cmpAddressLine1 { get; set; }
        public string cmpAddressLine2 { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public Nullable<System.DateTime> FStartDate { get; set; }
        public Nullable<System.DateTime> FEndDate { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public string Vat_Area { get; set; }
        public string Vat_RegiNo { get; set; }
        public Nullable<int> Bill_Invoice_Print_Type { get; set; }
    }
}
