//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuHeadWeb
    {
        public int MenuHeadWebID { get; set; }
        public string MenuHeadWebName { get; set; }
        public int Priority { get; set; }
        public string DivID { get; set; }
    }
}
