//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPermissionWeb
    {
        public int GrantID { get; set; }
        public Nullable<int> BrId { get; set; }
        public string UserID { get; set; }
        public int MenuHeadID { get; set; }
        public Nullable<int> SubMenuHeadID { get; set; }
        public int PageID { get; set; }
        public bool CanView { get; set; }
    }
}
