//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPageWeb
    {
        public int PageId { get; set; }
        public Nullable<int> SubMenuHeadID { get; set; }
        public int MenuHeadID { get; set; }
        public string PageName { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public bool IsRemoved { get; set; }
        public string PageTitle { get; set; }
        public string LiID { get; set; }
    }
}
