//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPOSEntities : DbContext
    {
        public SPOSEntities()
            : base("name=SPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankInfo> BankInfoes { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<MenuHeadWeb> MenuHeadWebs { get; set; }
        public virtual DbSet<MenuPageWeb> MenuPageWebs { get; set; }
        public virtual DbSet<MenuPermissionWeb> MenuPermissionWebs { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<Sale_Payment_Method> Sale_Payment_Method { get; set; }
        public virtual DbSet<T_BARCODE> T_BARCODE { get; set; }
        public virtual DbSet<T_Category> T_Category { get; set; }
        public virtual DbSet<T_Customer> T_Customer { get; set; }
        public virtual DbSet<T_CustomerDueCollection> T_CustomerDueCollection { get; set; }
        public virtual DbSet<T_DAMAGE> T_DAMAGE { get; set; }
        public virtual DbSet<T_Department> T_Department { get; set; }
        public virtual DbSet<T_Expenses> T_Expenses { get; set; }
        public virtual DbSet<T_GRN_DTL> T_GRN_DTL { get; set; }
        public virtual DbSet<T_GRN_MST> T_GRN_MST { get; set; }
        public virtual DbSet<T_PROD> T_PROD { get; set; }
        public virtual DbSet<T_SALES_DTL> T_SALES_DTL { get; set; }
        public virtual DbSet<T_SALES_MST> T_SALES_MST { get; set; }
        public virtual DbSet<T_SubCategory> T_SubCategory { get; set; }
        public virtual DbSet<T_Supplier> T_Supplier { get; set; }
        public virtual DbSet<T_SupplierPayment> T_SupplierPayment { get; set; }
        public virtual DbSet<T_UNIT> T_UNIT { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
