//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DAMAGE
    {
        public int DamageId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public string IUSER { get; set; }
        public string EUSER { get; set; }
        public Nullable<System.DateTime> IDAT { get; set; }
        public Nullable<System.DateTime> EDAT { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
