//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GRN_DTL
    {
        public int ReceiveDetailId { get; set; }
        public int ReceiveId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public int ProductID { get; set; }
        public string LotNo { get; set; }
        public int UnitId { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> ReturnQty { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
