//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GRN_MST
    {
        public int ReceiveId { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public string ReceiveNo { get; set; }
        public string InvoiceNo { get; set; }
        public int SupplierID { get; set; }
        public Nullable<bool> ApprovedStatus { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> CashPaid { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public string IUSER { get; set; }
        public string EUSER { get; set; }
        public Nullable<System.DateTime> IDAT { get; set; }
        public Nullable<System.DateTime> EDAT { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
