//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROD
    {
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string PBarcode { get; set; }
        public string PName { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public string Manufacture { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public Nullable<decimal> SalingPrice { get; set; }
    }
}
