//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SALES_MST
    {
        public int SlNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<short> SType { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> DiscountTk { get; set; }
        public Nullable<decimal> ReceiveAmount { get; set; }
        public Nullable<decimal> DueCollection { get; set; }
        public Nullable<decimal> CashPaid { get; set; }
        public Nullable<decimal> CashChange { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string CustName { get; set; }
        public string CustAddress { get; set; }
        public string CustPhone { get; set; }
        public string Description { get; set; }
        public string IUSER { get; set; }
        public string EUSER { get; set; }
        public Nullable<System.DateTime> IDAT { get; set; }
        public Nullable<System.DateTime> EDAT { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
