//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SALES_DTL
    {
        public int SlNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> SaleQty { get; set; }
        public Nullable<decimal> DisAomuntPerItems { get; set; }
        public Nullable<int> ReturnQty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string ReferenceInvoice { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
