//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SupplierPayment
    {
        public int SPId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<short> TrnType { get; set; }
        public Nullable<decimal> Due { get; set; }
        public string SPDescription { get; set; }
        public Nullable<short> Post { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
