//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UNIT
    {
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    }
}
